name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - develop

jobs:

  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      working-directory: ./backend
      run: mvn -B package --file pom.xml

  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
    - name: Build project
      working-directory: ./frontend
      run: npm run build --if-present
    - name: Run tests
      working-directory: ./frontend
      run: npm test
