name: Deploy

on:
  push:
    branches: [ develop ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Install 🔧
        working-directory: ./frontend
        run: npm ci
      - name: Build 🏗️
        working-directory: ./frontend
        run: npm run build -- --output-path ./dist --base-href https://mmosiur.github.io/appollo/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: ./frontend/dist
